import time

CONTAINER_SPACING = 0
CONTAINER_SIZE = [0, 0, 0, 0]
THUMBNAIL_SIZE = 100
HANDLE_WIDTH = 20
BG_COLOR = [.2, .2, .2, .5]
BG_COLOR_HOVER = [.4, .4, .4, .5]
ANIMATION_DURATION = 0.5
EXPAND_START = None
EXPAND_CLOSE = None
STARTING_WIDTH = 0
CONTAINER_WIDTH = 0
CURRENT_ASSET_INDEX = -1
LAST_KEY_INPUT = ""
LAST_KEY_TIME = time.time()
CURSOR_HAND = None
CURSOR_GRAB = None